---
- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_os_family }}.yml"

- name: install
  package: name=dma state=latest

- name: configure
  template:
    src: dma.conf.j2
    dest: "{{ rl_dma_config }}"
    owner: "{{ rl_dma_config_owner}}"
    group: "{{ rl_dma_config_group }}"
    mode: "u=rw,g=r,o="

- name: configure authorisation
  template:
    src: auth.conf.j2
    dest: "{{ rl_dma_auth }}"
    owner: "{{ rl_dma_config_owner }}"
    group: "{{ rl_dma_config_group }}"
    mode: "u=rw,g=r,o="
  when: rl_dma_user is defined or rl_dma_password is defined

- name: set alias to forward all mail
  lineinfile:
    dest: "{{ rl_dma_aliases }}"
    regexp: '^root:'
    line: "root: {{ rl_dma_alias_mail }}"
    backup: yes
  when: rl_dma_alias_mail is defined

- name: include FreeBSD specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

